using DataGenerator.API.Models;
using DataGenerator.API.Adapters;
using System.Text;

namespace DataGenerator.API.Exporters;

public class SqlDynamicExporter : IDynamicExporter
{
    private readonly IDatabaseAdapter _adapter;
    
    public SqlDynamicExporter(DatabaseType databaseType)
    {
        _adapter = databaseType switch
        {
            DatabaseType.MySQL => new MySqlAdapter(),
            DatabaseType.PostgreSQL => new PostgreSqlAdapter(),
            DatabaseType.MicrosoftSQLServer => new SqlServerAdapter(),
            DatabaseType.Oracle => new OracleAdapter(),
            DatabaseType.MongoDB => new MongoDbAdapter(),
            DatabaseType.Redis => new RedisAdapter(),
            _ => new MySqlAdapter()
        };
    }
    
    public string Export(List<Dictionary<string, object>> data, DynamicTableRequest request)
    {
        var sb = new StringBuilder();
        
        // Comentario con información
        sb.AppendLine($"// Generated by DataGenerator.API");
        sb.AppendLine($"// Database: {_adapter.Name}");
        sb.AppendLine($"// Table: {request.TableName}");
        sb.AppendLine($"// Records: {data.Count}");
        sb.AppendLine();
        
        // DDL (si aplica)
        sb.AppendLine(_adapter.GetCreateTableScript(request.TableName, request.Columns));
        sb.AppendLine();
        
        // Datos
        foreach (var row in data)
        {
            sb.AppendLine(_adapter.GetInsertScript(request.TableName, request.Columns, row));
        }
        
        return sb.ToString();
    }
    
    public string GetFileExtension()
    {
        if (_adapter is MongoDbAdapter) return ".js";
        if (_adapter is RedisAdapter) return ".redis";
        return ".sql";
    }
}