# DataGenerator.API - Script de mejoras arquitectonicas
# Ejecutar desde: C:\Users\Mariela\Documents\BD02\DataGenerator\DataGenerator.API

$ErrorActionPreference = "Stop"

Write-Host "Iniciando cambios en DataGenerator.API..." -ForegroundColor Cyan
Write-Host ""

# ---------------------------------------------------------------
# PASO 1 - Corregir Neo4jExporter.cs
# ---------------------------------------------------------------

Write-Host "PASO 1: Corrigiendo Neo4jExporter.cs..." -ForegroundColor Yellow

$neo4j = @"
using DataGenerator.API.Models;
using System.Text;

namespace DataGenerator.API.Exporters;

public class Neo4jExporter : IDynamicExporter
{
    public string Export(List<Dictionary<string, object>> data, DynamicTableRequest request)
    {
        var sb = new StringBuilder();

        sb.AppendLine(`$"// Cypher for {request.TableName}");
        sb.AppendLine();

        foreach (var row in data)
        {
            var props = new List<string>();
            foreach (var col in request.Columns)
            {
                var value = row[col.Name];
                string formattedValue = FormatCypherValue(value);
                props.Add(`$"{col.Name}: {formattedValue}");
            }

            sb.AppendLine(`$"CREATE (n:{request.TableName} {{{string.Join(", ", props)}}});");
        }

        return sb.ToString();
    }

    private string FormatCypherValue(object value)
    {
        if (value == null) return "null";

        if (value is bool b) return b ? "true" : "false";
        if (value is int || value is long || value is decimal || value is double)
            return value.ToString() ?? "0";
        if (value is DateTime dt)
            return `$"datetime('{dt:yyyy-MM-ddTHH:mm:ss}Z')";

        return `$"'{value.ToString()?.Replace("'", "\\'")}'";
    }

    public string GetFileExtension() => ".cypher";
}
"@

Set-Content "Neo4jExporter.cs" -Value $neo4j -Encoding UTF8
Write-Host "  OK Neo4jExporter.cs corregido" -ForegroundColor Green

# ---------------------------------------------------------------
# PASO 2 - Corregir SqlDynamicExporter.cs
# ---------------------------------------------------------------

Write-Host "PASO 2: Corrigiendo SqlDynamicExporter.cs..." -ForegroundColor Yellow

$sqlExp = @"
using DataGenerator.API.Models;
using DataGenerator.API.Adapters;
using System.Text;

namespace DataGenerator.API.Exporters;

public class SqlDynamicExporter : IDynamicExporter
{
    private readonly IDatabaseAdapter _adapter;

    public SqlDynamicExporter(DatabaseType databaseType)
    {
        _adapter = databaseType switch
        {
            DatabaseType.MySQL              => new MySqlAdapter(),
            DatabaseType.PostgreSQL         => new PostgreSqlAdapter(),
            DatabaseType.MicrosoftSQLServer => new SqlServerAdapter(),
            DatabaseType.Oracle             => new OracleAdapter(),
            _                               => new MySqlAdapter()
        };
    }

    public string Export(List<Dictionary<string, object>> data, DynamicTableRequest request)
    {
        var sb = new StringBuilder();

        sb.AppendLine(`$"// Generated by DataGenerator.API");
        sb.AppendLine(`$"// Database: {_adapter.Name}");
        sb.AppendLine(`$"// Table: {request.TableName}");
        sb.AppendLine(`$"// Records: {data.Count}");
        sb.AppendLine();

        sb.AppendLine(_adapter.GetCreateTableScript(request.TableName, request.Columns));
        sb.AppendLine();

        foreach (var row in data)
        {
            sb.AppendLine(_adapter.GetInsertScript(request.TableName, request.Columns, row));
        }

        return sb.ToString();
    }

    public string GetFileExtension() => ".sql";
}
"@

Set-Content "SqlDynamicExporter.cs" -Value $sqlExp -Encoding UTF8
Write-Host "  OK SqlDynamicExporter.cs corregido" -ForegroundColor Green

# ---------------------------------------------------------------
# PASO 3 - Crear IExporterFactory.cs
# ---------------------------------------------------------------

Write-Host "PASO 3: Creando IExporterFactory.cs..." -ForegroundColor Yellow

$iFactory = @"
using DataGenerator.API.Models;

namespace DataGenerator.API.Exporters;

public interface IExporterFactory
{
    IDynamicExporter Create(OutputFormat format, DatabaseType databaseType);
}
"@

Set-Content "IExporterFactory.cs" -Value $iFactory -Encoding UTF8
Write-Host "  OK IExporterFactory.cs creado" -ForegroundColor Green

# ---------------------------------------------------------------
# PASO 4 - Crear ExporterFactory.cs
# ---------------------------------------------------------------

Write-Host "PASO 4: Creando ExporterFactory.cs..." -ForegroundColor Yellow

$factory = @"
using DataGenerator.API.Models;

namespace DataGenerator.API.Exporters;

public class ExporterFactory : IExporterFactory
{
    public IDynamicExporter Create(OutputFormat format, DatabaseType databaseType)
    {
        return format switch
        {
            OutputFormat.Sql       => new SqlDynamicExporter(databaseType),
            OutputFormat.Json      => new JsonDynamicExporter(),
            OutputFormat.Csv       => new CsvDynamicExporter(),
            OutputFormat.MongoDb   => new MongoDbExporter(),
            OutputFormat.Redis     => new RedisExporter(),
            OutputFormat.Neo4j     => new Neo4jExporter(),
            OutputFormat.Cassandra => new CassandraExporter(),
            _                      => new JsonDynamicExporter()
        };
    }
}
"@

Set-Content "ExporterFactory.cs" -Value $factory -Encoding UTF8
Write-Host "  OK ExporterFactory.cs creado" -ForegroundColor Green

# ---------------------------------------------------------------
# PASO 5 - Actualizar GeneratorController.cs
# ---------------------------------------------------------------

Write-Host "PASO 5: Actualizando GeneratorController.cs..." -ForegroundColor Yellow

$controller = @"
using Microsoft.AspNetCore.Mvc;
using DataGenerator.API.Models;
using DataGenerator.API.Services;
using DataGenerator.API.Exporters;
using System.Text;

namespace DataGenerator.API.Controllers;

[ApiController]
[Route("api/[controller]")]
public class GeneratorController : ControllerBase
{
    private readonly IDynamicDataGenerator _generator;
    private readonly IExporterFactory _exporterFactory;

    public GeneratorController(IDynamicDataGenerator generator, IExporterFactory exporterFactory)
    {
        _generator = generator;
        _exporterFactory = exporterFactory;
    }

    [HttpPost("generate")]
    public IActionResult Generate([FromBody] DynamicTableRequest request)
    {
        try
        {
            if (request.Columns == null || !request.Columns.Any())
                return BadRequest(new { error = "Debes definir al menos una columna" });

            if (request.RecordCount > 100000)
                return BadRequest(new { error = "Maximo 100.000 registros por request" });

            var data = _generator.GenerateData(request);
            var exporter = _exporterFactory.Create(request.Format, request.DatabaseType);
            string content = exporter.Export(data, request);

            byte[] bytes = Encoding.UTF8.GetBytes(content);
            string fileName = `$"{request.TableName}_{DateTime.Now:yyyyMMdd_HHmmss}{exporter.GetFileExtension()}";
            return File(bytes, "application/octet-stream", fileName);
        }
        catch (Exception ex)
        {
            return StatusCode(500, new { error = ex.Message });
        }
    }

    [HttpGet("types")]
    public IActionResult GetAvailableTypes()
    {
        var types = Enum.GetNames(typeof(DataType))
            .Select(name => new { name, value = (int)Enum.Parse(typeof(DataType), name) })
            .ToList();

        return Ok(types);
    }
}
"@

Set-Content "GeneratorController.cs" -Value $controller -Encoding UTF8
Write-Host "  OK GeneratorController.cs actualizado" -ForegroundColor Green

# ---------------------------------------------------------------
# PASO 6 - Crear IDataGeneratorStrategy.cs
# ---------------------------------------------------------------

Write-Host "PASO 6: Creando IDataGeneratorStrategy.cs..." -ForegroundColor Yellow

$iStrategy = @"
using Bogus;
using DataGenerator.API.Models;

namespace DataGenerator.API.Strategies;

public interface IDataGeneratorStrategy
{
    string DomainName { get; }
    bool CanHandle(ColumnDefinition column);
    object GenerateValue(ColumnDefinition column, Faker faker);
}
"@

Set-Content "IDataGeneratorStrategy.cs" -Value $iStrategy -Encoding UTF8
Write-Host "  OK IDataGeneratorStrategy.cs creado" -ForegroundColor Green

# ---------------------------------------------------------------
# PASO 7 - Crear ECommerceStrategy.cs
# ---------------------------------------------------------------

Write-Host "PASO 7: Creando ECommerceStrategy.cs..." -ForegroundColor Yellow

$ecommerce = @"
using Bogus;
using DataGenerator.API.Models;

namespace DataGenerator.API.Strategies;

public class ECommerceStrategy : IDataGeneratorStrategy
{
    public string DomainName => "ecommerce";

    public bool CanHandle(ColumnDefinition column) =>
        string.Equals(column.Domain, "ecommerce", StringComparison.OrdinalIgnoreCase);

    public object GenerateValue(ColumnDefinition column, Faker faker)
    {
        return column.Type switch
        {
            DataType.ProductName        => faker.Commerce.ProductName(),
            DataType.ProductDescription => faker.Commerce.ProductDescription(),
            DataType.Price              => decimal.Parse(faker.Commerce.Price()),
            DataType.SKU                => faker.Commerce.Ean13(),
            DataType.CompanyName        => faker.Company.CompanyName(),
            DataType.Email              => faker.Internet.Email(),
            DataType.FullName           => faker.Name.FullName(),
            DataType.Phone              => faker.Phone.PhoneNumber(),
            DataType.Address            => faker.Address.FullAddress(),
            DataType.City               => faker.Address.City(),
            DataType.Country            => faker.Address.Country(),
            _                           => faker.Commerce.ProductName()
        };
    }
}
"@

Set-Content "ECommerceStrategy.cs" -Value $ecommerce -Encoding UTF8
Write-Host "  OK ECommerceStrategy.cs creado" -ForegroundColor Green

# ---------------------------------------------------------------
# PASO 8 - Crear BankingStrategy.cs
# ---------------------------------------------------------------

Write-Host "PASO 8: Creando BankingStrategy.cs..." -ForegroundColor Yellow

$banking = @"
using Bogus;
using DataGenerator.API.Models;

namespace DataGenerator.API.Strategies;

public class BankingStrategy : IDataGeneratorStrategy
{
    public string DomainName => "banking";

    public bool CanHandle(ColumnDefinition column) =>
        string.Equals(column.Domain, "banking", StringComparison.OrdinalIgnoreCase);

    public object GenerateValue(ColumnDefinition column, Faker faker)
    {
        return column.Type switch
        {
            DataType.FullName         => faker.Name.FullName(),
            DataType.Email            => faker.Internet.Email(),
            DataType.Phone            => faker.Phone.PhoneNumber(),
            DataType.CreditCardNumber => faker.Finance.CreditCardNumber(),
            DataType.CreditCardType   => faker.Finance.CreditCardCvv(),
            DataType.Amount           => faker.Finance.Amount(),
            DataType.IBAN             => faker.Finance.Iban(),
            DataType.Currency         => faker.Finance.Currency().Code,
            DataType.CompanyName      => faker.Company.CompanyName(),
            DataType.Address          => faker.Address.FullAddress(),
            DataType.City             => faker.Address.City(),
            DataType.Country          => faker.Address.Country(),
            _                         => faker.Finance.Amount().ToString()
        };
    }
}
"@

Set-Content "BankingStrategy.cs" -Value $banking -Encoding UTF8
Write-Host "  OK BankingStrategy.cs creado" -ForegroundColor Green

# ---------------------------------------------------------------
# PASO 9 - Actualizar ColumnDefinition.cs
# ---------------------------------------------------------------

Write-Host "PASO 9: Actualizando ColumnDefinition.cs..." -ForegroundColor Yellow

$colDef = @"
namespace DataGenerator.API.Models;

public class ColumnDefinition
{
    public string Name { get; set; } = string.Empty;
    public DataType Type { get; set; }
    public object? MinValue { get; set; }
    public object? MaxValue { get; set; }
    public int? MaxLength { get; set; }
    public List<string>? PossibleValues { get; set; }
    public bool IsNullable { get; set; } = false;
    public object? DefaultValue { get; set; }
    public string? Format { get; set; }
    public string? Domain { get; set; }
}
"@

Set-Content "ColumnDefinition.cs" -Value $colDef -Encoding UTF8
Write-Host "  OK ColumnDefinition.cs actualizado" -ForegroundColor Green

# ---------------------------------------------------------------
# PASO 10 - Actualizar Program.cs
# ---------------------------------------------------------------

Write-Host "PASO 10: Actualizando Program.cs..." -ForegroundColor Yellow

$program = @"
using DataGenerator.API.Services;
using DataGenerator.API.Exporters;
using DataGenerator.API.Strategies;
using DataGenerator.API.Generators;
using DataGenerator.API.Generators.Generators;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddScoped<IDynamicDataGenerator, DynamicDataGenerator>();

builder.Services.AddSingleton<IExporterFactory, ExporterFactory>();

builder.Services.AddSingleton<IDataGeneratorStrategy, ECommerceStrategy>();
builder.Services.AddSingleton<IDataGeneratorStrategy, BankingStrategy>();

builder.Services.AddSingleton<FullNameGenerator>();
builder.Services.AddSingleton<EmailGenerator>();
builder.Services.AddSingleton<CityGenerator>();
builder.Services.AddSingleton<CreditCardGenerator>();

var app = builder.Build();

app.UseCors(policy => policy.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader());
app.UseSwagger();
app.UseSwaggerUI();
app.MapControllers();

app.Run();
"@

Set-Content "Program.cs" -Value $program -Encoding UTF8
Write-Host "  OK Program.cs actualizado" -ForegroundColor Green

# ---------------------------------------------------------------
# PASO 11 - Compilar
# ---------------------------------------------------------------

Write-Host ""
Write-Host "PASO 11: Compilando proyecto..." -ForegroundColor Yellow
Write-Host ""

dotnet build

Write-Host ""
Write-Host "=============================================" -ForegroundColor Cyan
Write-Host "Archivos procesados:" -ForegroundColor Cyan
Write-Host "  CORREGIDO  Neo4jExporter.cs" -ForegroundColor White
Write-Host "  CORREGIDO  SqlDynamicExporter.cs" -ForegroundColor White
Write-Host "  NUEVO      IExporterFactory.cs" -ForegroundColor Green
Write-Host "  NUEVO      ExporterFactory.cs" -ForegroundColor Green
Write-Host "  NUEVO      IDataGeneratorStrategy.cs" -ForegroundColor Green
Write-Host "  NUEVO      ECommerceStrategy.cs" -ForegroundColor Green
Write-Host "  NUEVO      BankingStrategy.cs" -ForegroundColor Green
Write-Host "  MODIFICADO GeneratorController.cs" -ForegroundColor Yellow
Write-Host "  MODIFICADO ColumnDefinition.cs" -ForegroundColor Yellow
Write-Host "  MODIFICADO Program.cs" -ForegroundColor Yellow
Write-Host "=============================================" -ForegroundColor Cyan
