# DataGenerator.API - Script de REVERSION TOTAL
# Ejecutar desde: C:\Users\Mariela\Documents\BD02\DataGenerator\DataGenerator.API

$ErrorActionPreference = "Stop"

Write-Host "Revirtiendo todos los cambios del script anterior..." -ForegroundColor Red
Write-Host ""

# ---------------------------------------------------------------
# PASO 1 - Eliminar archivos nuevos creados por el script
# ---------------------------------------------------------------

Write-Host "PASO 1: Eliminando archivos nuevos..." -ForegroundColor Yellow

$archivosNuevos = @(
    "IExporterFactory.cs",
    "ExporterFactory.cs",
    "IDataGeneratorStrategy.cs",
    "ECommerceStrategy.cs",
    "BankingStrategy.cs"
)

foreach ($archivo in $archivosNuevos) {
    if (Test-Path $archivo) {
        Remove-Item $archivo -Force
        Write-Host "  ELIMINADO $archivo" -ForegroundColor Red
    } else {
        Write-Host "  NO EXISTE (ya limpio) $archivo" -ForegroundColor Gray
    }
}

# ---------------------------------------------------------------
# PASO 2 - Restaurar Neo4jExporter.cs original
# ---------------------------------------------------------------

Write-Host ""
Write-Host "PASO 2: Restaurando Neo4jExporter.cs original..." -ForegroundColor Yellow

$neo4j = @'
using DataGenerator.API.Models;
using System.Text;

namespace DataGenerator.API.Exporters;

public class Neo4jExporter : IDynamicExporter
{
    public string Export(List<Dictionary<string, object>> data, DynamicTableRequest request)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine($"// Cypher for {request.TableName}");
        sb.AppendLine();
        
        foreach (var row in data)
        {
            var props = new List<string>();
            foreach (var col in request.Columns)
            {
                var value = row[col.Name];
                string formattedValue = FormatCypherValue(value);
                props.Add($"{col.Name}: {formattedValue}");
            }
            
            sb.AppendLine($"CREATE (n:{request.TableName} {{{string.Join(", ", props)}}});");
        }
        
        return sb.ToString();
    }
    
    private string FormatCypherValue(object value)
    {
        if (value == null) return "null";
        
        if (value is bool b) return b ? "true" : "false";
        if (value is int || value is long || value is decimal || value is double)
            return value.ToString() ?? "0";
        if (value is DateTime dt)
            return $"datetime('{dt:yyyy-MM-ddTHH:mm:ss}Z')";
        
        return $"'{value.ToString()?.Replace("'", "\\'")}'";
    }
    
    public string GetFileExtension() => "cypher";
}
'@

Set-Content "Neo4jExporter.cs" -Value $neo4j -Encoding UTF8
Write-Host "  OK Neo4jExporter.cs restaurado" -ForegroundColor Green

# ---------------------------------------------------------------
# PASO 3 - Restaurar SqlDynamicExporter.cs original
# ---------------------------------------------------------------

Write-Host "PASO 3: Restaurando SqlDynamicExporter.cs original..." -ForegroundColor Yellow

$sqlExp = @'
using DataGenerator.API.Models;
using DataGenerator.API.Adapters;
using System.Text;

namespace DataGenerator.API.Exporters;

public class SqlDynamicExporter : IDynamicExporter
{
    private readonly IDatabaseAdapter _adapter;
    
    public SqlDynamicExporter(DatabaseType databaseType)
    {
        _adapter = databaseType switch
        {
            DatabaseType.MySQL => new MySqlAdapter(),
            DatabaseType.PostgreSQL => new PostgreSqlAdapter(),
            DatabaseType.MicrosoftSQLServer => new SqlServerAdapter(),
            DatabaseType.Oracle => new OracleAdapter(),
            DatabaseType.MongoDB => new MongoDbAdapter(),
            DatabaseType.Redis => new RedisAdapter(),
            _ => new MySqlAdapter()
        };
    }
    
    public string Export(List<Dictionary<string, object>> data, DynamicTableRequest request)
    {
        var sb = new StringBuilder();
        
        // Comentario con informacion
        sb.AppendLine($"// Generated by DataGenerator.API");
        sb.AppendLine($"// Database: {_adapter.Name}");
        sb.AppendLine($"// Table: {request.TableName}");
        sb.AppendLine($"// Records: {data.Count}");
        sb.AppendLine();
        
        // DDL (si aplica)
        sb.AppendLine(_adapter.GetCreateTableScript(request.TableName, request.Columns));
        sb.AppendLine();
        
        // Datos
        foreach (var row in data)
        {
            sb.AppendLine(_adapter.GetInsertScript(request.TableName, request.Columns, row));
        }
        
        return sb.ToString();
    }
    
    public string GetFileExtension()
    {
        if (_adapter is MongoDbAdapter) return ".js";
        if (_adapter is RedisAdapter) return ".redis";
        return ".sql";
    }
}
'@

Set-Content "SqlDynamicExporter.cs" -Value $sqlExp -Encoding UTF8
Write-Host "  OK SqlDynamicExporter.cs restaurado" -ForegroundColor Green

# ---------------------------------------------------------------
# PASO 4 - Restaurar GeneratorController.cs original
# ---------------------------------------------------------------

Write-Host "PASO 4: Restaurando GeneratorController.cs original..." -ForegroundColor Yellow

$controller = @'
using Microsoft.AspNetCore.Mvc;
using DataGenerator.API.Models;
using DataGenerator.API.Services;
using DataGenerator.API.Exporters;
using System.Text;

namespace DataGenerator.API.Controllers;

[ApiController]
[Route("api/[controller]")]
public class GeneratorController : ControllerBase
{
    private readonly IDynamicDataGenerator _generator;
    
    public GeneratorController(IDynamicDataGenerator generator)
    {
        _generator = generator;
    }
    
    [HttpPost("generate")]
    public IActionResult Generate([FromBody] DynamicTableRequest request)
    {
        try
        {
            if (request.Columns == null || !request.Columns.Any())
            {
                return BadRequest(new { error = "Debes definir al menos una columna" });
            }
            
            var data = _generator.GenerateData(request);
            
            Console.WriteLine($"Formato recibido: {request.Format}");
            
            IDynamicExporter exporter = request.Format switch
            {
                OutputFormat.Sql => new SqlDynamicExporter(request.DatabaseType),
                OutputFormat.Json => new JsonDynamicExporter(),
                OutputFormat.Csv => new CsvDynamicExporter(),
                OutputFormat.MongoDb => new MongoDbExporter(),
                OutputFormat.Redis => new RedisExporter(),
                OutputFormat.Neo4j => new Neo4jExporter(),
                OutputFormat.Cassandra => new CassandraExporter(),
                _ => new JsonDynamicExporter()
            };
            
            string content = exporter.Export(data, request);
            
            Console.WriteLine($"Contenido generado (primeros 200 chars): {content.Substring(0, Math.Min(200, content.Length))}");
            
            byte[] bytes = Encoding.UTF8.GetBytes(content);
            string fileName = $"{request.TableName}_{DateTime.Now:yyyyMMdd_HHmmss}{exporter.GetFileExtension()}";
            
            return File(bytes, "application/octet-stream", fileName);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
            return StatusCode(500, new { error = ex.Message });
        }
    }

    [HttpGet("types")]
    public IActionResult GetAvailableTypes()
    {
        var types = Enum.GetNames(typeof(DataType))
            .Select(name => new { name, value = (int)Enum.Parse(typeof(DataType), name) })
            .ToList();
        
        return Ok(types);
    }
}
'@

Set-Content "GeneratorController.cs" -Value $controller -Encoding UTF8
Write-Host "  OK GeneratorController.cs restaurado" -ForegroundColor Green

# ---------------------------------------------------------------
# PASO 5 - Restaurar ColumnDefinition.cs original
# ---------------------------------------------------------------

Write-Host "PASO 5: Restaurando ColumnDefinition.cs original..." -ForegroundColor Yellow

$colDef = @'
using System.ComponentModel.DataAnnotations;

namespace DataGenerator.API.Models;

public class ColumnDefinition
{
    public string Name { get; set; } = string.Empty;
    public DataType Type { get; set; }
    public object? MinValue { get; set; }
    public object? MaxValue { get; set; }
    public int? MaxLength { get; set; }
    public List<string>? PossibleValues { get; set; }
    public bool IsNullable { get; set; } = false;
    public object? DefaultValue { get; set; }
    public string? Format { get; set; }
}
'@

Set-Content "ColumnDefinition.cs" -Value $colDef -Encoding UTF8
Write-Host "  OK ColumnDefinition.cs restaurado" -ForegroundColor Green

# ---------------------------------------------------------------
# PASO 6 - Restaurar Program.cs original
# ---------------------------------------------------------------

Write-Host "PASO 6: Restaurando Program.cs original..." -ForegroundColor Yellow

$program = @'
using DataGenerator.API.Services;
using DataGenerator.API.Generators;
using DataGenerator.API.Generators.Generators;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

// Registrar servicios
builder.Services.AddScoped<IDynamicDataGenerator, DynamicDataGenerator>();

// Registrar todos los generadores semanticos
builder.Services.AddSingleton<FullNameGenerator>();
builder.Services.AddSingleton<EmailGenerator>();
builder.Services.AddSingleton<CityGenerator>();
builder.Services.AddSingleton<CreditCardGenerator>();

var app = builder.Build();

app.UseCors(policy => policy.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader());
app.UseSwagger();
app.UseSwaggerUI();
app.MapControllers();

app.Run();
'@

Set-Content "Program.cs" -Value $program -Encoding UTF8
Write-Host "  OK Program.cs restaurado" -ForegroundColor Green

# ---------------------------------------------------------------
# PASO 7 - Compilar para verificar que el proyecto quedo limpio
# ---------------------------------------------------------------

Write-Host ""
Write-Host "PASO 7: Compilando para verificar estado limpio..." -ForegroundColor Yellow
Write-Host ""

dotnet build

Write-Host ""
Write-Host "=============================================" -ForegroundColor Cyan
Write-Host "REVERSION COMPLETADA" -ForegroundColor Cyan
Write-Host "=============================================" -ForegroundColor Cyan
Write-Host "  ELIMINADOS: IExporterFactory.cs" -ForegroundColor Red
Write-Host "  ELIMINADOS: ExporterFactory.cs" -ForegroundColor Red
Write-Host "  ELIMINADOS: IDataGeneratorStrategy.cs" -ForegroundColor Red
Write-Host "  ELIMINADOS: ECommerceStrategy.cs" -ForegroundColor Red
Write-Host "  ELIMINADOS: BankingStrategy.cs" -ForegroundColor Red
Write-Host "  RESTAURADO: Neo4jExporter.cs" -ForegroundColor Green
Write-Host "  RESTAURADO: SqlDynamicExporter.cs" -ForegroundColor Green
Write-Host "  RESTAURADO: GeneratorController.cs" -ForegroundColor Green
Write-Host "  RESTAURADO: ColumnDefinition.cs" -ForegroundColor Green
Write-Host "  RESTAURADO: Program.cs" -ForegroundColor Green
Write-Host "=============================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "El proyecto debe compilar igual que antes de cualquier cambio." -ForegroundColor White
