from faker import Faker
import random
import uuid

fake = Faker("es_ES")
fake_en = Faker("en_US")

CATEGORY_NAMES = [
    "Electronica", "Ropa", "Hogar", "Deportes", "Alimentos", "Juguetes",
    "Libros", "Musica", "Vehiculos", "Salud", "Belleza", "Jardineria",
    "Oficina", "Mascotas", "Viajes", "Arte", "Herramientas", "Joyeria",
    "Informatica", "Telefonia", "Television", "Audio", "Fotografia", "Gaming",
    "Cocina", "Muebles", "Decoracion", "Iluminacion", "Textiles", "Calzado",
    "Accesorios", "Relojes", "Gafas", "Perfumeria", "Cosmetica", "Higiene",
    "Farmacia", "Nutricion", "Fitness", "Ciclismo", "Natacion", "Camping",
    "Pesca", "Caza", "Equitacion", "Golf", "Tenis", "Futbol", "Baloncesto",
    "Beisbol", "Rugby", "Atletismo", "Yoga", "Pilates", "Artes Marciales",
    "Educacion", "Papeleria", "Manualidades", "Coleccionismo", "Antiguedades",
    "Instrumentos Musicales", "Partituras", "Cine", "Teatro", "Danza",
    "Pintura", "Escultura", "Fotografia Artistica", "Diseño Grafico",
    "Arquitectura", "Ingenieria", "Medicina", "Derecho", "Economia",
    "Psicologia", "Sociologia", "Historia", "Geografia", "Filosofia",
    "Religion", "Idiomas", "Literatura", "Poesia", "Comics", "Manga",
    "Infantil", "Juvenil", "Adultos", "Tercera Edad", "Maternidad",
    "Bebes", "Embarazo", "Fertilidad", "Gerontologia", "Veterinaria",
    "Agricultura", "Ganaderia", "Piscicultura", "Apicultura", "Viticultura",
    "Panaderia", "Pasteleria", "Chocolateria", "Cafeteria", "Heladeria",
    "Carniceria", "Pescaderia", "Fruteria", "Verduleria", "Especias",
    "Vinos", "Cervezas", "Destilados", "Bebidas", "Infusiones",
    "Suplementos", "Vitaminas", "Proteinas", "Dietetica", "Organicos",
    "Vegano", "Vegetariano", "Sin Gluten", "Sin Lactosa", "Kosher",
    "Climatizacion", "Fontaneria", "Electricidad", "Albañileria", "Pintura Hogar",
    "Carpinteria", "Cerrajeria", "Jardineria Exterior", "Piscinas", "Barbacoas",
    "Automocion", "Motocicletas", "Bicicletas", "Nautica", "Aeronautica",
    "Ferroviario", "Transporte", "Logistica", "Mudanzas", "Mensajeria",
    "Seguros", "Banca", "Inversiones", "Criptomonedas", "Fintech",
    "Inmobiliaria", "Alquiler", "Hipotecas", "Tasaciones", "Reformas",
    "Turismo", "Hoteles", "Restaurantes", "Cruceros", "Aventura",
    "Ecoturismo", "Turismo Rural", "Turismo Urbano", "Turismo Cultural", "Turismo Activo",
    "Seguridad", "Vigilancia", "Alarmas", "Camaras", "Control Acceso",
    "Telecomunicaciones", "Internet", "Redes", "Servidores", "Cloud",
    "Software", "Aplicaciones", "Videojuegos", "Realidad Virtual", "Inteligencia Artificial",
    "Robotica", "Drones", "Impresion 3D", "Domótica", "Energia Solar",
    "Energia Eolica", "Reciclaje", "Sostenibilidad", "Medio Ambiente", "Ecologia",
]

def _unique_category(existing: set = None) -> str:
    available = [c for c in CATEGORY_NAMES if existing is None or c not in existing]
    if available:
        return random.choice(available)
    suffix = random.randint(100, 9999)
    base = random.choice(CATEGORY_NAMES)
    return f"{base} {suffix}"

TABLE_CONTEXT_MAP = {
    "categoria": {"nombre": lambda: random.choice(CATEGORY_NAMES)},
    "categorias": {"nombre": lambda: random.choice(CATEGORY_NAMES)},
    "category": {"nombre": lambda: random.choice(CATEGORY_NAMES)},
    "categories": {"nombre": lambda: random.choice(CATEGORY_NAMES)},
    "producto": {"nombre": lambda: fake_en.catch_phrase()},
    "productos": {"nombre": lambda: fake_en.catch_phrase()},
    "product": {"nombre": lambda: fake_en.catch_phrase()},
    "products": {"nombre": lambda: fake_en.catch_phrase()},
    "ciudad": {"nombre": lambda: fake.city()},
    "ciudades": {"nombre": lambda: fake.city()},
    "pais": {"nombre": lambda: fake.country()},
    "paises": {"nombre": lambda: fake.country()},
    "empresa": {"nombre": lambda: fake.company()},
    "empresas": {"nombre": lambda: fake.company()},
    "rol": {"nombre": lambda: random.choice(["Administrador", "Usuario", "Moderador", "Invitado", "Supervisor", "Analista"])},
    "roles": {"nombre": lambda: random.choice(["Administrador", "Usuario", "Moderador", "Invitado", "Supervisor", "Analista"])},
    "departamento": {"nombre": lambda: random.choice(["Ventas", "Marketing", "TI", "RRHH", "Finanzas", "Legal", "Operaciones", "Logistica", "Compras", "Produccion"])},
    "departamentos": {"nombre": lambda: random.choice(["Ventas", "Marketing", "TI", "RRHH", "Finanzas", "Legal", "Operaciones", "Logistica", "Compras", "Produccion"])},
}

FIELD_MAP = {
    "nombre": lambda: fake.first_name(),
    "name": lambda: fake.first_name(),
    "first_name": lambda: fake.first_name(),
    "apellido": lambda: fake.last_name(),
    "last_name": lambda: fake.last_name(),
    "apellido_materno": lambda: fake.last_name(),
    "apellido_paterno": lambda: fake.last_name(),
    "nombre_completo": lambda: fake.name(),
    "full_name": lambda: fake.name(),
    "apodo": lambda: fake_en.user_name(),
    "username": lambda: fake_en.user_name(),
    "usuario": lambda: fake_en.user_name(),
    "email": lambda: fake.email(),
    "correo": lambda: fake.email(),
    "correo_electronico": lambda: fake.email(),
    "telefono": lambda: fake.phone_number(),
    "phone": lambda: fake.phone_number(),
    "celular": lambda: fake.phone_number(),
    "movil": lambda: fake.phone_number(),
    "direccion": lambda: fake.address().replace("\n", ", "),
    "address": lambda: fake.address().replace("\n", ", "),
    "calle": lambda: fake.street_address(),
    "ciudad": lambda: fake.city(),
    "city": lambda: fake.city(),
    "pais": lambda: fake.country(),
    "country": lambda: fake.country(),
    "estado": lambda: random.choice(["activo", "inactivo", "pendiente", "completado", "cancelado"]),
    "status": lambda: random.choice(["active", "inactive", "pending", "completed", "cancelled"]),
    "provincia": lambda: fake.state(),
    "region": lambda: fake.state(),
    "codigo_postal": lambda: fake.postcode(),
    "zip_code": lambda: fake.postcode(),
    "dni": lambda: fake.numerify(text="########"),
    "ruc": lambda: fake.numerify(text="###########"),
    "cedula": lambda: fake.numerify(text="##########"),
    "fecha_nacimiento": lambda: fake.date_of_birth(minimum_age=18, maximum_age=80).isoformat(),
    "birth_date": lambda: fake.date_of_birth(minimum_age=18, maximum_age=80).isoformat(),
    "fecha_creacion": lambda: fake.date_time_this_decade().isoformat(),
    "fecha_actualizacion": lambda: fake.date_time_this_year().isoformat(),
    "created_at": lambda: fake.date_time_this_decade().isoformat(),
    "updated_at": lambda: fake.date_time_this_year().isoformat(),
    "fecha": lambda: fake.date_this_decade().isoformat(),
    "date": lambda: fake.date_this_decade().isoformat(),
    "fecha_inicio": lambda: fake.date_this_year().isoformat(),
    "fecha_fin": lambda: fake.date_between(start_date="+1d", end_date="+1y").isoformat(),
    "fecha_vencimiento": lambda: fake.date_between(start_date="+30d", end_date="+2y").isoformat(),
    "fecha_pedido": lambda: fake.date_time_this_year().isoformat(),
    "fecha_entrega": lambda: fake.date_between(start_date="+1d", end_date="+30d").isoformat(),
    "salario": lambda: round(random.uniform(1000, 8000), 2),
    "salary": lambda: round(random.uniform(1000, 8000), 2),
    "sueldo": lambda: round(random.uniform(1000, 8000), 2),
    "precio": lambda: round(random.uniform(5, 2000), 2),
    "price": lambda: round(random.uniform(5, 2000), 2),
    "monto": lambda: round(random.uniform(10, 5000), 2),
    "amount": lambda: round(random.uniform(10, 5000), 2),
    "total": lambda: round(random.uniform(10, 10000), 2),
    "subtotal": lambda: round(random.uniform(10, 9000), 2),
    "descuento": lambda: round(random.uniform(0, 50), 2),
    "impuesto": lambda: round(random.uniform(0, 300), 2),
    "balance": lambda: round(random.uniform(-1000, 10000), 2),
    "saldo": lambda: round(random.uniform(0, 10000), 2),
    "costo": lambda: round(random.uniform(5, 5000), 2),
    "empresa": lambda: fake.company(),
    "company": lambda: fake.company(),
    "cargo": lambda: fake.job(),
    "job": lambda: fake.job(),
    "puesto": lambda: fake.job(),
    "departamento": lambda: random.choice(["Ventas", "Marketing", "TI", "RRHH", "Finanzas", "Operaciones"]),
    "department": lambda: random.choice(["Sales", "Marketing", "IT", "HR", "Finance", "Operations"]),
    "producto": lambda: fake_en.catch_phrase(),
    "product": lambda: fake_en.catch_phrase(),
    "descripcion": lambda: fake.sentence(nb_words=10),
    "description": lambda: fake.sentence(nb_words=10),
    "categoria": lambda: random.choice(CATEGORY_NAMES),
    "category": lambda: random.choice(CATEGORY_NAMES),
    "marca": lambda: fake_en.company(),
    "brand": lambda: fake_en.company(),
    "sku": lambda: fake_en.bothify(text="SKU-####-??").upper(),
    "codigo": lambda: fake_en.bothify(text="COD-######"),
    "code": lambda: fake_en.bothify(text="COD-######"),
    "cantidad": lambda: random.randint(1, 100),
    "quantity": lambda: random.randint(1, 100),
    "stock": lambda: random.randint(0, 500),
    "edad": lambda: random.randint(18, 80),
    "age": lambda: random.randint(18, 80),
    "peso": lambda: round(random.uniform(45, 120), 1),
    "calificacion": lambda: round(random.uniform(1, 5), 1),
    "rating": lambda: round(random.uniform(1, 5), 1),
    "score": lambda: random.randint(0, 100),
    "porcentaje": lambda: round(random.uniform(0, 100), 2),
    "tipo": lambda: random.choice(["tipo_a", "tipo_b", "tipo_c"]),
    "type": lambda: random.choice(["type_a", "type_b", "type_c"]),
    "rol": lambda: random.choice(["admin", "usuario", "moderador", "invitado"]),
    "role": lambda: random.choice(["admin", "user", "moderator", "guest"]),
    "nivel": lambda: random.choice(["basico", "intermedio", "avanzado", "experto"]),
    "prioridad": lambda: random.choice(["baja", "media", "alta", "critica"]),
    "url": lambda: fake.url(),
    "website": lambda: fake.url(),
    "ip": lambda: fake.ipv4(),
    "ip_address": lambda: fake.ipv4(),
    "token": lambda: fake_en.sha256(),
    "password": lambda: fake_en.sha256(),
    "contrasena": lambda: fake_en.sha256(),
    "uuid": lambda: str(uuid.uuid4()),
    "titulo": lambda: fake.sentence(nb_words=5).rstrip("."),
    "title": lambda: fake.sentence(nb_words=5).rstrip("."),
    "contenido": lambda: fake.paragraph(nb_sentences=3),
    "content": lambda: fake.paragraph(nb_sentences=3),
    "comentario": lambda: fake.sentence(nb_words=12),
    "comment": lambda: fake.sentence(nb_words=12),
    "nota": lambda: fake.sentence(nb_words=8),
    "resumen": lambda: fake.paragraph(nb_sentences=2),
    "slug": lambda: fake.slug(),
    "color": lambda: fake.color_name(),
    "color_hex": lambda: fake.hex_color(),
    "imagen": lambda: fake.image_url(),
    "image": lambda: fake.image_url(),
    "foto": lambda: fake.image_url(),
    "avatar": lambda: fake.image_url(),
    "archivo": lambda: fake.file_name(),
    "activo": lambda: random.choice([True, False]),
    "active": lambda: random.choice([True, False]),
    "habilitado": lambda: random.choice([True, False]),
    "verificado": lambda: random.choice([True, False]),
    "banco": lambda: random.choice(["BCP", "BBVA", "Interbank", "Scotiabank", "BanBif"]),
    "metodo_pago": lambda: random.choice(["efectivo", "tarjeta", "transferencia", "yape", "plin"]),
    "moneda": lambda: random.choice(["PEN", "USD", "EUR", "MXN", "COP"]),
}

def generate_by_field_name(field_name: str, table_name: str = None) -> any:
    key = field_name.lower().strip()
    table_key = (table_name or "").lower().strip()

    if table_key and table_key in TABLE_CONTEXT_MAP:
        table_overrides = TABLE_CONTEXT_MAP[table_key]
        if key in table_overrides:
            return table_overrides[key]()

    if key in FIELD_MAP:
        return FIELD_MAP[key]()

    return None
